const js = require('@eslint/js');
const globals = require('globals');
const babelParser = require('@babel/eslint-parser');
const importPlugin = require('eslint-plugin-import');
const react = require('eslint-plugin-react');
const jest = require('eslint-plugin-jest');
const prettierPlugin = require('eslint-plugin-prettier');
const prettierConfig = require('eslint-config-prettier');
const jsxA11y = require('eslint-plugin-jsx-a11y');

module.exports = [
  // Standalone global ignores
  {
    ignores: [
      // Logs
      'logs/**',
      '*.log',

      // Runtime data
      'pids/**',
      '*.pid',
      '*.seed',

      // Directory for instrumented libs generated by jscoverage/JSCover
      'lib-cov/**',

      // Coverage directory used by tools like istanbul
      'coverage/**',

      // Grunt intermediate storage
      '.grunt/**',

      // node-waf configuration
      '.lock-wscript',

      // Compiled binary addons
      'build/Release/**',
      '.eslintcache',

      // Dependency directory
      'node_modules/**',

      // OSX
      '**/.DS_Store',

      // flow-typed
      'flow-typed/npm/**',

      // App packaged
      'release/**',
      'app/main.prod.js',
      'app/main.prod.js.map',
      'app/main.prod.js.LICENSE',
      'app/main.prod.js.LICENSE.txt',
      'app/renderer.prod.js',
      'app/renderer.prod.js.map',
      'app/worker.prod.js',
      'app/worker.prod.js.map',
      'app/preload.prod.js',
      'app/preload.prod.js.map',
      'app/style.css',
      'app/style.css.map',
      'app/dist/**',
      'dist/**',
      'dll/**',
      'main.js',
      'main.js.map',

      '.idea/**',
      'npm-debug.log.*',
      '**/__snapshots__/**',

      // Configs/Package
      'package.json',
      '.travis.yml',
      'configs/*.cjs',
    ],
  },

  // Base JS / JSX files configuration
  {
    files: ['**/*.{js,jsx}'],
    languageOptions: {
      parser: babelParser,
      parserOptions: {
        requireConfigFile: false,
        babelOptions: {
          babelrc: false,
          configFile: require.resolve('./babel.config.js'),
        },
      },
      globals: {
        ...globals.browser,
        ...globals.node,
      },
    },
    plugins: {
      import: importPlugin,
      react,
      prettier: prettierPlugin,
      'jsx-a11y': jsxA11y,
    },
    rules: {
      ...js.configs.recommended.rules,
      'no-useless-escape': 0,
      'preserve-caught-error': 0,
      'no-useless-assignment': 0,
      'react/destructuring-assignment': 0,
      'class-methods-use-this': 0,
      'no-plusplus': 0,
      'no-console': 0,
      'no-param-reassign': ['error', { props: false }],
      'import/no-extraneous-dependencies': ['error', { packageDir: __dirname }],
      'react/jsx-filename-extension': [1, { extensions: ['.js', '.jsx'] }],
      'react/prefer-stateless-function': 0,
      'react/forbid-prop-types': 0,
      'react/no-children-prop': 0,
      'no-nested-ternary': 0,
      'prefer-regex-literals': 0,
      'no-unused-vars': 0,
      curly: ['error', 'all'],
    },
    settings: {
      react: {
        version: 'detect',
      },
      'import/resolver': {
        webpack: {
          config: require.resolve('./configs/webpack.config.eslint.js'),
        },
      },
    },
  },

  // Test files configuration
  {
    files: ['test/**/*.{js,jsx}', '**/*.spec.{js,jsx}', '**/*.test.{js,jsx}'],
    languageOptions: {
      globals: {
        ...globals.jest,
      },
    },
    plugins: {
      jest,
    },
    rules: {
      'jest/no-disabled-tests': 'warn',
      'jest/no-focused-tests': 'error',
      'jest/no-identical-title': 'error',
      'jest/no-commented-out-tests': 0,
      'jest/no-standalone-expect': 0,
      'jest/expect-expect': 0,
    },
  },

  // Turn off conflicting formatting rules for Prettier
  prettierConfig,
];
